apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-deployer-binding
  namespace: dev-jenkins
subjects:
- kind: ServiceAccount
  name: jenkins-user
  namespace: dev-jenkins
roleRef:
  kind: Role
  name: jenkins-deployer
  apiGroup: rbac.authorization.k8s.io


# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: jenkins-cluster-deployer-binding
# subjects:
# - kind: ServiceAccount
#   name: jenkins-user
#   namespace: dev-jenkins
# roleRef:
#   kind: ClusterRole
#   name: jenkins-cluster-deployer
#   apiGroup: rbac.authorization.k8s.io
